# For the "s" tool. See https://github.com/ahawkins/bindir for more
s_src_dir: "{{ '~/Developer' | expanduser }}"

brew_prefix: "{{ (ansible_facts.architecture == 'x86_64') | ternary('/usr/local', '/opt/homebrew') }}"
