# Names of keys in the secret store. These are used with a lookup when
# the value is needed. Otherwise they are passed pass to the lookup.
keys:
  brew_api_token: comp.brew.api_token
  mas_account: comp.mas.account
  mas_password: comp.mas.password

# For the "s" tool. See https://github.com/ahawkins/bindir for more
s_src_dir: ~/src

dotfiles_dir: "{{ s_src_dir }}/ahawkins/dotfiles"
