# Names of keys in the secret store. These are used with a lookup when
# the value is needed. Otherwise they are passed pass to the lookup.
keys:
  brew_api_token: comp.brew.api_token
  mas_account: comp.mas.account
  mas_password: comp.mas.password
  life_key: comp.life.deploy_key
  difm: comp.difm.key

# For the "s" tool. See https://github.com/ahawkins/bindir for more
s_src_dir: ~/src

music_dir: ~/music

gopath: ~/go

# Location for ahawkins/life repo
life_dir: ~/life

dotfiles_dir: "{{ s_src_dir }}/ahawkins/dotfiles"
bindir_dir: "{{ s_src_dir }}/ahawkins/bindir"
