comp_username: ahawkins

# For the "s" tool. See https://github.com/ahawkins/bindir for more
s_src_dir: "{{ '~/Developer' | expanduser }}"

dotfiles_dir: "{{ s_src_dir }}/ahawkins/dotfiles"

brew_prefix: "{{ (ansible_facts.architecture == 'x86_64') | ternary('/usr/local', '/opt/homebrew') }}"

ansible_python_interpreter: "{{ ansible_playbook_python }}"