---
casks:
  - spotify
  - the-unarchiver
  - vlc
  - font-lato

apps:
  - "411643860"  # DaisyDisk
  - "803453959"  # Slack
  - "747648890"  # Spotify
  - "557168941"  # Tweebot

remove_from_dock:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Pages
  - Numbers
  - Keynote
  - iTunes
  - iBooks
  - App Store
  - Siri

dock_items:
  - name: iTerm
    path: "/Applications/iTerm.app"
    position: 1
  - name: Chrome
    path: "/Applications/Google Chrome.app"
    position: 2
  - name: Slack
    path: "/Applications/Slack.app"
    position: 3
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    position: 6

# FIXME: seems there is a bug where "ansible_user" is undefined when evaluating this file.
# The bug did not exist when evaluated in the playbook.
aws_access_key_id: "{{ lookup('keyring', '{} {}'.format('comp.skillshare.aws.admin.access_key_id', 'ahawkins')) }}"
aws_secret_access_key: "{{ lookup('keyring', '{} {}'.format('comp.skillshare.aws.admin.secret_access_key', 'ahawkins')) }}"
github_access_token: "{{ lookup('keyring', '{} {}'.format('comp.skillshare.github.access_token', 'ahawkins')) }}"

aws_profiles:
  - name: skillshare-admin
    region: us-east-1

  - name: skillshare-staging
    region: us-east-1
    source_profile: skillshare-admin
    role_arn: "arn:aws:iam::{{ lookup('env', 'SKILLSHARE_AWS_PROD_ACCOUNT_ID') }}:role/administrator"

  - name: skillshare-production
    region: us-east-1
    source_profile: skillshare-admin
    role_arn: "arn:aws:iam::{{ lookup('env', 'SKILLSHARE_AWS_PROD_ACCOUNT_ID') }}:role/administrator"

  - name: skillshare-utility
    region: us-east-1
    source_profile: skillshare-admin
    role_arn: "arn:aws:iam::{{ lookup('env', 'SKILLSHARE_AWS_UTILITY_ACCOUNT_ID') }}:role/administrator"

kops_contexts:
  - name: skillshare-prod
    cluster: "{{ lookup('env', 'SKILLSHARE_PROD_CLUSTER') }}"
    namespace: prod

  - name: skillshare-qa
    cluster: "{{ lookup('env', 'SKILLSHARE_QA_CLUSTER') }}"
    namespace: qa-master

eks_contexts:
  - name: skillshare-utility
    cluster: "{{ lookup('env', 'SKILLSHARE_UTILITY_CLUSTER') }}"
    namespace: tools

  - name: skillshare-staging
    cluster: "{{ lookup('env', 'SKILLSHARE_STAGING_CLUSTER') }}"
    namespace: staging
