---
casks:
  - spotify
  - the-unarchiver
  - vlc
  - font-lato

apps:
  - "411643860"  # DaisyDisk
  - "803453959"  # Slack
  - "747648890"  # Spotify
  - "557168941"  # Tweebot

remove_from_dock:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Pages
  - Numbers
  - Keynote
  - iTunes
  - iBooks
  - App Store
  - Siri

dock_items:
  - name: iTerm
    path: "/Applications/iTerm.app"
    position: 1
  - name: Chrome
    path: "/Applications/Google Chrome.app"
    position: 2
  - name: Slack
    path: "/Applications/Slack.app"
    position: 3
  - name: Notes
    path: "/Applications/Notes.app"
    position: 4
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    position: 6
