---
casks:
  - font-lato

# FIXME: seems there is a bug where "ansible_user" is undefined when evaluating this file.
# The bug did not exist when evaluated in the playbook.
aws_access_key_id: "{{ lookup('keyring', '{} {}'.format('comp.skillshare.aws.access_key_id', comp_username)) }}"
aws_secret_access_key: "{{ lookup('keyring', '{} {}'.format('comp.skillshare.aws.secret_access_key', comp_username)) }}"
