---
- name: Tap cask
  homebrew_tap:
    state: present
    name: "{{ item }}"
  with_items:
      - homebrew/cask-fonts
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install packages
  homebrew:
    state: present
    name: "{{ packages }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install casks
  homebrew_cask:
    state: present
    name: "{{ casks }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Create fish vendor_functions.d
  become: true
  file:
    state: directory
    dest: /usr/local/share/fish/vendor_functions.d

- name: Install fundle
  become: true
  get_url:
    url: https://git.io/fundle
    dest: /usr/local/share/fish/vendor_functions.d/fundle.fish

- name: Add fish to /etc/shells
  become: true
  lineinfile:
    state: present
    dest: /etc/shells
    regexp: fish
    line: /usr/local/bin/fish

- name: Create configuration directory
  file:
    state: directory
    path: ~/.config/env/comp

- name: Configure environment variables
  template:
    src: "{{ item }}"
    dest: ~/.config/env/comp/{{ item | basename }}
  with_fileglob:
    - files/env/*

- name: Create source code directory
  file:
    state: directory
    path: "{{ s_src_dir }}"

- name: Accept github key
  known_hosts:
    state: present
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

- name: Check dotfiles
  stat:
    path: "{{ dotfiles_dir }}"
  register: dotfiles_stat

- name: Clone dotfiles
  git:
    repo: https://github.com/ahawkins/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    version: master
    update: true
  when: dotfiles_stat.stat.isdir == False

- name: Configure dotfiles to push over SSH
  command: git remote set-url --push origin git@github.com:ahawkins/dotfiles.git
  args:
    chdir: "{{ dotfiles_dir }}"
  changed_when: false
