---
- name: Tap cask
  homebrew_tap:
    state: present
    name: "{{ item }}"
  with_items:
      - caskroom/cask
      - caskroom/fonts
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install packages
  homebrew:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ packages }}"

- name: Install casks
  homebrew_cask:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ casks }}"

- name: Add fish to /etc/shells
  become: true
  lineinfile:
    state: present
    dest: /etc/shells
    regexp: fish
    line: /usr/local/bin/fish

- name: Create configuration directory
  file:
    state: directory
    path: ~/.config/comp

# - name: Generate environment file
#   template:
#     src: files/env.fish
#     dest: ~/.config/comp/env.fish
#
# - name: Create env.d directory
#   file:
#     state: directory
#     dest: ~/.config/comp/env.d

- name: Create source code directory
  file:
    state: directory
    path: "{{ s_src_dir }}"

- name: Accept github key
  known_hosts:
    state: present
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

- name: Clone dotfiles
  git:
    repo: https://github.com/ahawkins/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    version: refactor/stow
    update: true
  register: dotfiles_source

- name: Configure dotfiles to push over SSH
  command: git remote set-url --push origin git@github.com:ahawkins/dotfiles.git
  args:
    chdir: "{{ dotfiles_dir }}"
  changed_when: false

- name: Install dotfiles
  make:
    target: install
    chdir: "{{ dotfiles_dir }}"
  when: dotfiles_source.changed
