---
- name: Install packages
  pacman:
    state: present
    name: "{{ item }}"
  become: true
  with_items: "{{ packages }}"

- file:
    state: directory
    path: "{{ opt_dir }}"
  become: true

- name: Create env directory
  file:
    state: directory
    path: "{{ env_auto_dir }}"

- name: Set environment variables
  template:
    src: "files/{{ item }}"
    dest: "{{ env_auto_dir }}/{{ item }}"
  with_items:
    - JOURNAL_DIR
    - LIFE_DIR
    - S_SRC_DIR

- name: Create source code directory
  file:
    state: directory
    path: "{{ s_src_dir }}"

- name: Accept github key
  known_hosts:
    state: present
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

- name: Install fundle
  get_url:
    url: "https://git.io/fundle"
    dest: "/usr/share/fish/functions/fundle.fish"
    mode: "u+x,o+x,g+x"
  become: true

- name: Clone bindir
  git:
    repo: https://github.com/ahawkins/bindir.git
    dest: "{{ bindir_dir }}"
    update: false

- name: Configure bindir to push over SSH
  command: git remote set-url --push origin git@github.com:ahawkins/bindir.git
  args:
    chdir: "{{ bindir_dir }}"
  changed_when: False

- name: Create s config dir
  file:
    state: directory
    dest: ~/.config/s/aliases

- name: Create s aliases
  copy:
    dest: "~/.config/s/aliases/{{ item.name }}"
    content: "{{ item.dest }}"
  with_items: "{{ s_aliases }}"
