---
- name: Install casks
  homebrew:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ packages }}"

- name: Install casks
  homebrew_cask:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ casks }}"

- name: Install apps
  mas_app:
    state: present
    name: "{{ item }}"
  with_items: "{{ apps }}"

- name: Create comp configuration
  file:
    state: directory
    path: ~/.config/comp

- name: Apply git configuration
  copy:
    path: files/gitconfig
    path: ~/.config/comp/git
