---
- name: Install casks
  community.general.homebrew_cask:
    state: present
    name: "{{ casks }}"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Create ev dir
  ansible.builtin.file:
    state: directory
    path: ~/.config/env/skillshare

- name: Create comp configuration
  ansible.builtin.file:
    state: directory
    path: ~/.config/comp

- name: Copy comp configuration file
  ansible.builtin.copy:
    src: files/comp/env.fish
    dest: ~/.config/comp/env.fish

- name: Copy comp files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/comp/{{ item | basename }}
  loop: "{{ query('fileglob', 'files/comp/*') }}"

- name: Creat config directory
  ansible.builtin.file:
    state: directory
    path: ~/.config/skillshare

- name: Copy config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/skillshare/{{ item | basename }}
  loop: "{{ query('fileglob', 'files/config/*') }}"

- name: Configure environment variables
  ansible.builtin.copy:
    content: "{{ item.value }}\n"
    dest: ~/.config/env/comp/{{ item.key }}
  loop: "{{ env | dict2items }}"
  when: env is defined
  loop_control:
    label: "{{ item.key }}"

- name: Create ev files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/.config/skillshare/{{ item | basename }}
  loop: "{{ query('fileglob', 'files/env/*') }}"

- name: Remove dead environment variables
  ansible.builtin.file:
    state: absent
    dest: ~/.config/env/comp/{{ item }}
  loop:
    - AWS_DEFAULT_PROFILE
    - AWS_PROFILE
    - KOP_STATE_STORE
    - SKILLSHARE_AWS_ADMIN_ACCOUNT_ID
    - SKILLSHARE_AWS_PROD_ACCOUNT_ID
    - SKILLSHARE_AWS_UTILITY_ACCOUNT_ID
    - SKILLSHARE_DATA_SCIENCE_CLUSTER
    - SKILLSHARE_PROD_CLUSTER
    - SKILLSHARE_QA_CLUSTER
    - SKILLSHARE_SANDBOX_CLUSTER
    - SKILLSHARE_STAGING_CLUSTER
    - SKILLSHARE_UTILITY_CLUSTER
    - SKILLSHARE_GITHUB_ACCESS_TOKEN

- name: Create source directory
  ansible.builtin.file:
    state: directory
    path: "{{ s_src_dir }}/skillshare"
