---
- name: Install casks
  homebrew:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ packages }}"

- name: Install casks
  homebrew_cask:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ casks }}"

- name: Install apps
  mas_app:
    state: present
    name: "{{ item }}"
  with_items: "{{ apps }}"

- name: Remove junk dock items
  osx_dock:
    state: absent
    name: "{{ item }}"
  with_items: "{{ remove_from_dock }}"

- name: Add dock items
  osx_dock:
    state: present
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items: "{{ dock_items }}"

- name: Order dock items
  osx_dock:
    state: present
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    position: "{{ item.position }}"
  with_items: "{{ dock_items }}"
