---
- hosts: localhost
  connection: local
  vars:
    difm_stations:
      - name: ambient_hi
        title: DI.FM - Ambient (Hi)
      - name: trance_hi
        title: DI.FM - Trance (Hi)
      - name: chillout_hi
        title: DI.FM - Chillout (Hi)
      - name: darkpsytrance_hi
        title: DI.FM - Dark Psy (Hi)
      - name: goapsy_hi
        title: DI.FM - Goa Psy (Hi)
      - name: melodicprogressive_hi
        title: DI.FM - Modelodic Progressive (Hi)
      - name: progressivepsy_hi
        title: DI.FM - Progressive Psy (Hi)
      - name: progressive_hi
        title: DI.FM - Progressive (Hi)
      - name: psybient_hi
        title: DI.FM - Psybient (Hi)
      - name: psychill_hi
        title: DI.FM - Psychill (Hi)
      - name: spacemusic_hi
        title: DI.FM - Space Dreams (Hi)
      - name: vocalchillout_hi
        title: DI.FM - Vocal Chillout (Hi)
      - name: vocaltrance_hi
        title: DI.FM - Vocal Trance (Hi)
      - name: vocallounge_hi
        title: DI.FM - Vocal Lounge (Hi)
    directories:
      - playlists
  tasks:
    - name: Create directories
      file:
        state: directory
        path: "{{ music_dir }}/{{ item }}"
      with_items: "{{ directories }}"

    - name: Create DI.fm playlist
      template:
        src: files/difm.pls
        dest: "{{ music_dir }}/playlists/difm.pls"
      vars:
        entries: "{{ difm_stations }}"
