---
- hosts: localhost
  connection: local
  vars:
    difm_stations:
      - name: ambient
        title: DI.FM - Ambient
      - name: trance
        title: DI.FM - Trance
      - name: chillout
        title: DI.FM - Chillout
      - name: darkpsytrance
        title: DI.FM - Dark Psy
      - name: goapsy
        title: DI.FM - Goa Psy
      - name: melodicprogressive
        title: DI.FM - Modelodic Progressive
      - name: progressivepsy
        title: DI.FM - Progressive Psy
      - name: progressive
        title: DI.FM - Progressive
      - name: psybient
        title: DI.FM - Psybient
      - name: psychill
        title: DI.FM - Psychill
      - name: spacemusic
        title: DI.FM - Space Dreams
      - name: vocalchillout
        title: DI.FM - Vocal Chillout
      - name: vocaltrance
        title: DI.FM - Vocal Trance
      - name: vocallounge
        title: DI.FM - Vocal Lounge
    directories:
      - playlists
  tasks:
    - name: Create directories
      file:
        state: directory
        path: "{{ music_dir }}/{{ item }}"
      with_items: "{{ directories }}"

    - name: Create DI.fm playlist
      template:
        src: files/difm.pls
        dest: "{{ music_dir }}/playlists/difm.pls"
      vars:
        entries: "{{ difm_stations }}"
