---
- hosts: localhost
  connection: local
  tasks:
    - name: Delete ~/.ssh/config
      file:
        state: absent
        dest: ~/.ssh/config

    - name: Create SSH conf.d directory
      file:
        state: directory
        dest: ~/.config/ssh/conf.d

    - name: Add ssh global host config file
      copy:
        src: files/ssh/hosts
        dest: ~/.config/ssh/conf.d/hosts
