---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - item in vars
          - vars[item] | default('') | length > 0
        fail_msg: "Required variable '{{ item }}' is not defined or is empty."
        success_msg: "Required variable '{{ item }}' is properly set"
      loop:
        - homebrew_api_token
        - github_token
        - aws_access_key_id
        - aws_secret_access_key
  roles:
    - terminal
    - shell
    - development
    - yubikey
    - slashdeploy
    - osx
