---
- hosts: localhost
  connection: local
  vars:
    dead_items:
      - Launchpad
      - Mail
      - Safari
      - Contacts
      - Notes
      - Reminders
      - Maps
      - Photos
      - Messages
      - FaceTime
      - iTunes
      - iBooks
      - App Store
      - Calendar
      - Google Chrome
    keep_items:
      - name: iTerm
        path: "/Applications/iTerm.app"
        position: 1
      - name: Vivaldi
        path: "/Applications/Vivaldi.app"
        position: 2
      - name: Tweetbot
        path: "/Applications/Tweetbot.app"
        position: 3
      - name: Telegram
        path: "/Applications/Telegram.app"
        position: 4
      - name: Slack
        path: "/Applications/Slack.app"
        position: 5
      - name: System Preferences
        path: "/Applications/System Preferences.app"
        position: 6
  tasks:
    - name: Remove junk dock items
      osx_dock:
        state: absent
        name: "{{ item }}"
      with_items: "{{ dead_items }}"

    - name: Add dock items
      osx_dock:
        state: present
        name: "{{ item.name }}"
        path: "{{ item.path }}"
      with_items: "{{ keep_items }}"

    - name: Order dock items
      osx_dock:
        state: present
        name: "{{ item.name }}"
        path: "{{ item.path }}"
        position: "{{ item.position }}"
      with_items: "{{ keep_items }}"
