---
- hosts: localhost
  connection: local
  vars:
    taps:
      - caskroom/cask
      - caskroom/fonts
      - caskroom/versions
    brews:
      - bats
      - curl
      - direnv
      - editorconfig
      - exif
      - docker # just the client
      - dockutil
      - ffmpeg
      - fish
      - git
      - go
      - gnupg21
      - htop-osx
      - hub
      - imagemagick
      - jq
      - ledger
      - mas
      - parallel
      - pinentry-mac
      - reattach-to-user-namespace
      - ssh-copy-id
      - rename
      - tarsnap
      - tarsnapper
      - the_silver_searcher
      - tmux
      - todo-txt
      - trash
      - tree
      - unrar
      - vim
      - watch
      - wget
      - ykneomgr
      - youtube-dl
    casks:
      - flux
      - font-input
      - font-lato
      - font-source-code-pro
      - google-chrome
      - keybase
      - minikube
      - iterm2
      - skype
      - spotify
      - the-unarchiver
      - vagrant
      - veracrypt
      - virtualbox
      - vivaldi
      - vlc
      - whatsapp
    apps:
      - "411643860" # DaisyDisk
      - "406056744" # Evernote
      - "407963104" # Pixelmator
      - "803453959" # Slack
      - "425955336" # Skitch
      - "747648890" # Spotify
      - "747648890" # Telegram
      - "557168941" # Tweebot
      - "461369673" # VOX
  tasks:
    - name: Add brew taps
      homebrew_tap:
        state: present
        name: "{{ item }}"
      environment:
        HOMEBREW_GITHUB_API_TOKEN: "{{ lookup('secret', keys.brew_api_token) }}"
      with_items: "{{ taps }}"

    - name: Install brew packages
      homebrew:
        state: present
        name: "{{ item }}"
      environment:
        HOMEBREW_GITHUB_API_TOKEN: "{{ lookup('secret', keys.brew_api_token) }}"
      with_items: "{{ brews }}"

    - name: Install casks
      homebrew_cask:
        state: present
        name: "{{ item }}"
      environment:
        HOMEBREW_GITHUB_API_TOKEN: "{{ lookup('secret', keys.brew_api_token) }}"
      with_items: "{{ casks }}"

    - name: Login to App Store
      mas_login:
        state: present
        email: "{{ lookup('secret', keys.mas_account) }}"
        password: "{{ lookup('secret', keys.mas_password) }}"

    - name: Install apps
      mas_app:
        state: present
        name: "{{ item }}"
      with_items: "{{ apps }}"

    - name: Add fish to /etc/shells
      become: true
      lineinfile:
        state: present
        dest: /etc/shells
        regexp: fish
        line: /usr/local/bin/fish

    - name: Add OSX executables
      become: true
      copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item | basename }}"
        mode: 0755
      with_fileglob:
        - files/osx/bin/*

    - name: configure git to use gpg2 executable
      git_config:
        name: gpg.program
        scope: system
        value: gpg2
