---
- hosts: localhost
  connection: local
  tasks:
    - name: Create ssh config file
      file:
        state: touch
        dest: ~/.ssh/config
        mode: "0600"
      changed_when: false

    - name: Add generic SSH configuration
      blockinfile:
        state: present
        dest: ~/.ssh/config
        marker: "# {mark} ANSIBLE MANAGED BLOCK [GENERIC]"
        content: |
          Host *
            ServerAliveInterval 30
