---
- hosts: localhost
  connection: local
  vars:
    - homebrew_api_token: "{{ lookup('keyring', '{} {}'.format(keys.brew_api_token, ansible_user)) }}"
  roles:
    - terminal
    - shell
    - development
    - yubikey
    - skillshare
