---
- hosts: localhost
  connection: local
  vars:
    deps:
      - golang.org/x/net
      - golang.org/x/tools
      - github.com/cmars/represent
    installs:
      - golang.org/x/tools/cmd/present
      - github.com/cmars/represent
  tasks:
    - name: Create go directories
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - "{{ gopath }}"
        - "{{ gopath }}/bin"

    - name: Get dependencies
      command: "go get {{ item }}"
      args:
        creates: "{{ gopath }}/src/{{ item }}"
      environment:
        # The ~ is not expanded in this case.
        GOPATH: "{{ gopath | replace('~', lookup('env', 'HOME')) }}"
      with_items: "{{ deps }}"

    - name: Install programs
      command: "go install {{ item }}"
      args:
        creates: "{{ gopath }}/src/{{ item }}"
      environment:
        # The ~ is not expanded in this case.
        GOPATH: "{{ gopath | replace('~', lookup('env', 'HOME')) }}"
      with_items: "{{ installs }}"
