---
aws_default_region: us-east-1

aws_access_key_id: "{{ lookup('keyring', '{} {}'.format('comp.slashdeploy.aws.access_key_id', comp_username)) }}"
aws_secret_access_key: "{{ lookup('keyring', '{} {}'.format('comp.slashdeploy.aws.secret_access_key', comp_username)) }}"

casks:
  - descript
  - focusrite-control
