---
packages:
  - curl
  - editorconfig
  - exif
  - ffmpeg
  - git
  - gnupg
  - htop-osx
  - imagemagick
  - jq
  - parallel
  - rename
  - ssh-copy-id
  - the_silver_searcher
  - tmux
  - trash
  - tree
  - unrar
  - vim
  - watch
  - wget
  - youtube-dl
