---
- name: Add taps
  community.general.homebrew_tap:
    state: present
    name:
      - go-task/homebrew-tap
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install packages
  community.general.homebrew:
    state: present
    name: "{{ packages }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install casks
  community.general.homebrew_cask:
    state: present
    name: "{{ casks }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install asdf-vm
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    version: "v{{ asdf_version }}"
    update: false
    dest: ~/.asdf

- name: List asdf-vm plugins
  ansible.builtin.command: "bash -c 'source ~/.asdf/asdf.sh && asdf plugin-list'"
  register: installed_asdf_plugins
  changed_when: false

- name: Install asdf-vm plugins
  ansible.builtin.command: "bash -c 'source ~/.asdf/asdf.sh && asdf plugin-add {{ item }}'"
  when: "not item in installed_asdf_plugins.stdout"
  loop: "{{ asdf_plugins }}"
