---
- name: Tap cask
  homebrew_tap:
    state: present
    name: caskroom/cask
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install packages
  homebrew:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ packages }}"

- name: Install casks
  homebrew_cask:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ casks }}"

# - name: Check minikube status
#   command: minikube status
#   changed_when: False
#   register: status
#
# - name: Create minikube
#   command: minikube start
#   when: "status.stdout.find('Does Not Exist') != -1"
#
# - command: minikube stop
#   when: "status.stdout.find('Does Not Exist') != -1"

- name: Disable minikube update notifications
  command: minikube config set WantUpdateNotification false
  changed_when: false

- name: Configure ahawkins AWS access key
  command: aws --profile ahawkins configure set aws_access_key_id "{{ lookup('keyring', '{} {}'.format(keys.aws_ahawkins_access_key_id, ansible_user)) }}"
  changed_when: false

- name: Configure ahawkins AWS secret key
  command: aws --profile ahawkins configure set aws_secret_access_key "{{ lookup('keyring', '{} {}'.format(keys.aws_ahawkins_secret_access_key, ansible_user)) }}"
  changed_when: false

- name: Configure ahawkins AWS region
  command: aws --profile ahawkins configure set region '{{ aws_ahawkins_default_region }}'
  changed_when: false
