---
- name: Install packages
  homebrew:
    state: present
    name: "{{ packages }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install casks
  homebrew_cask:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ casks }}"

- name: Disable minikube update notifications
  command: minikube config set WantUpdateNotification false
  changed_when: false

