---
- name: Generate locales
  locale_gen:
    state: present
    name: "{{ item }}"
  become: true
  with_items: "{{ locales }}"

- name: Install packages
  pacman:
    state: present
    name: "{{ item }}"
  become: true
  with_items: "{{ packages }}"

- name: Get mirrorlist config
  stat:
    path: /etc/pacman.d/mirrorlist
  register: mirror_list

- name: Rank mirrors
  command: "reflector -n {{ mirrors }} --sort rate --save /etc/pacman.d/mirrorlist"
  become: true
  when: "(mirror_list.stat.mtime | int) > mirror_list_expiry"

- name: Sync pacman
  pacman:
    update_cache: true
  become: true
  when: "(mirror_list.stat.mtime | int) > mirror_list_expiry"
