---
- name: Install packages
  pacman:
    state: present
    name: "{{ item }}"
  become: true
  with_items: "{{ packages }}"

- name: Enable pcscd service
  systemd:
    enabled: true
    name: pcscd.service
  become: true
