#!/usr/bin/env bash

set -euo pipefail

main() {
	if [ -z "${1:-}" ]; then
		echo "USAGE: ${0} [user@]HOST [...ANSIBLE_ARGS]" 1>&2
		return 1
	fi

	if [ ! -f remote_vars/become.yml ]; then
		echo "Create ansible_become_password in remote_vars/become.yml for remote configuration" 1>&2
		return 1
	fi

	if [ ! -f remote_vars/localhost.yml ]; then
		echo "Create remote_vars/localhost.yml for remote configuration" 1>&2
		return 1
	fi

	host="${1}"

	shift

	ssh -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' "${host}" 'mkdir -p ~/.comp'
	rsync -avzh --delete --exclude .git  --exclude remove_vars/  -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' . "${host}:.comp"
	scp remote_vars/become.yml "${host}:.comp/become.yml"
	scp remote_vars/localhost.yml "${host}:.comp/host_vars/localhost.yml"
	ssh "${host}" "sh -c 'cd ~/.comp && script/configure $*'"
}

main "$@"
