#!/usr/bin/env bash

set -euo pipefail

if [ -z "${1:-}" ]; then
	echo "USAGE: ${0} [user@]HOST" 1>&2
	exit 1
fi

# ssh-copy-id "${1}"

ssh -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' "${1}" 'mkdir -p ~/.comp'
rsync -avzh --delete -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' . "${1}:.comp"
ssh "${1}" 'cd ~/.comp && script/configure'
