#!/usr/bin/env bash

set -euo pipefail

main() {
	if [ -z "${1:-}" ]; then
		echo "USAGE: ${0} [user@]HOST [...ANSIBLE_ARGS]" 1>&2
		return 1
	fi

	if [ ! -f become.yml ]; then
		echo "Create ansible_become_password in become.yml for remote configuration" 1>&2
		return 1
	fi

	host="${1}"

	shift

	ssh -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' "${host}" 'mkdir -p ~/.comp'
	rsync -avzh --delete --exclude .git -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' . "${host}:.comp"
	ssh "${host}" "sh -c 'cd ~/.comp && script/configure $*'"
}

main "$@"
