---
- name: Tap cask
  community.general.homebrew_tap:
    state: present
    name: "{{ item }}"
  loop:
      - homebrew/cask-drivers
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Install casks
  community.general.homebrew_cask:
    state: present
    name: "{{ casks }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Check AWS caller identity
  amazon.aws.aws_caller_info:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "us-east-1"

- name: Configure AWS access key
  ansible.builtin.command: aws --profile slashdeploy configure set aws_access_key_id '{{ aws_access_key_id }}'
  changed_when: false

- name: Configure AWS secret key
  ansible.builtin.command: aws --profile slashdeploy configure set aws_secret_access_key '{{ aws_secret_access_key }}'
  changed_when: false

- name: Configure ahawkins AWS region
  ansible.builtin.command: aws --profile slashdeploy configure set region '{{ aws_default_region }}'
  changed_when: false

- name: Check profile
  amazon.aws.aws_caller_info:
    profile: slashdeploy
    region: us-east-1
