---
- name: Install casks
  community.general.homebrew_cask:
    state: present
    name: "{{ casks }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"

- name: Check AWS caller identity
  amazon.aws.aws_caller_info:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "us-east-1"

- name: Configure AWS profile
  community.aws.aws_config:
    profile: slashdeploy
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_default_region }}"

- name: Check profile
  amazon.aws.aws_caller_info:
    profile: slashdeploy
    region: us-east-1
