---
- name: Install packages
  pacman:
    state: present
    name: "{{ item }}"
  become: true
  with_items: "{{ packages }}"

- name: Configure xorg
  copy:
    src: touchpad.conf
    dest: /etc/X11/xorg.conf.d/touchpad.conf
  become: true
