---
- name: Install mas
  homebrew:
    state: present
    name: "{{ item }}"
  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ homebrew_api_token }}"
  with_items: "{{ packages }}"

- name: Login to app store
  mas_login:
    state: present
    email: "{{ lookup('keyring', '{} {}'.format(keys.mas_account, ansible_user)) }}"
    password: "{{ lookup('keyring', '{} {}'.format(keys.mas_password, ansible_user)) }}"
